### ISSUE TITLE
Issue with menu bar when used in Mobile aspect ratio

### ISSUE THREAD

**Issue by Bhargav02550** [nani-samireddy/open-portfolio#8]
Hey @nani-samireddy ,
Your portfolio is really amazing but recently i had cam through a small bug in the application.
When using in mobile ration the menu bar keeps scrolling without staying at a fixed position causing confusion of how to close the menu bar.

**Comment by nani-samireddy** [comment]
Hi @Bhargav02550,

Thank you for pointing out that, Will add a fix to that ASAP

**Comment by Bhargav02550** [comment]
Can you asigin it to me so that I can fix it .

**Comment by nani-samireddy** [comment]
Sure @Bhargav02550 

Assigning it to you ✅
